Problem: We need to add a stream for publishing EULA acceptance infor…
42ity/fty-proto pull request #38
Opened 2018-04-18 12:57 UTC by jana-rapava

…mation.

Solution: Do it.
*******************************************
Size: S
Impact: S

Signed-off-by: Jana Rapava <janarapava@eaton.com>

2018-04-18 13:23 UTC, EldoreiJK commented
LGTM

2018-04-18 13:29 UTC, michal42 requested changes
fty_proto.h is generated from fty_proto.xml. Also, since this is an official stream now, shouldn't there be a protocol for the messages passed over it (again described in fty_proto.xml)?

2018-04-18 13:53 UTC, jana-rapava commented
@michal42 Ack. In the meantime, could you please update the README with the right way to edit this project?

2018-04-19 07:25 UTC, michal42 approved these changes

2018-04-24 11:22 UTC, merged