METRICS bnf decription was broken
42ity/fty-proto pull request #49
Opened 2018-09-14 08:49 UTC by geraldguillaume

Problem: f21956b5bf1b9d325af0b530b144564c6a84e030 commit broke METRICS description
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>

2018-09-14 09:31 UTC, EldoreiJK commented
Just checking, isn't .bnf autogenerated?

2018-09-17 08:14 UTC, jimklimov requested changes

2018-09-17 08:14 UTC, jimklimov commented on src/fty_proto.bnf
> +Value defines duration of validity (i.e. how long is metric valid,
Looking at the referenced commit, the comment about "Value defined ..." should be up there near the TTL field; I am not sure how it should be formatted (e.g. indented or prefixed with semicolons) to make a proper BNF markup. If indentation matters, then maybe the end of line introduced before "unixtime" was the problem.

Is there some parser to check validity of a BNF text?

2018-09-17 08:52 UTC, jimklimov commented on src/fty_proto.bnf
> +Value defines duration of validity (i.e. how long is metric valid,
I found a http://www.icosaedro.it/bnf_chk/bnf_chk-on-line.html which complains on every other line we have (the non-empty ones ;P) but generally it seems that windy comment paragraphs' lines not starting with a comment character (semicolon or hash as that tool insists) are a major problem.

2018-09-17 08:54 UTC, jimklimov commented on src/fty_proto.bnf
> +Value defines duration of validity (i.e. how long is metric valid,
Note that Pieter mentioned that BNF in his experience was a buzzword for something that some strange people want to put into their documentation books to pass some customer acceptance requirements but never use in practice, e.g. for machine parsing, although they could... so it was likely never a priority to make the generator a very correct one.

2024-07-25 07:46 UTC, closed without merging